# Generated by Django 3.2.8 on 2021-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='component', max_length=32)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
