# Generated by Django 3.2.8 on 2021-10-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='name',
            field=models.CharField(default='component', max_length=32),
        ),
    ]
