# Generated by Django 3.2.8 on 2021-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assetrelation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='lastname',
            field=models.CharField(default='component', max_length=32),
        ),
    ]
