# Generated by Django 3.2.8 on 2021-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assetrelation_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='second_name',
            field=models.CharField(default='component', max_length=32),
        ),
    ]
