# Generated by Django 3.2.8 on 2021-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assetrelation_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='description',
            field=models.CharField(default='component', max_length=32),
        ),
    ]
