# Generated by Django 3.2.9 on 2021-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assetrelation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='ojo',
            field=models.CharField(default='component', max_length=32),
        ),
    ]
